// TermsAndConditions.tsx
import { CircleChevronLeft } from "lucide-react";
import React from "react";

interface TermsAndConditionsProps {
  companyName?: string;
  contactEmail?: string;
  lastUpdated?: string;
}

const TermsAndConditions: React.FC<TermsAndConditionsProps> = ({
  companyName = "AdStreamAI",
  contactEmail = "contact@adstreamai.com",
  lastUpdated = "December 1, 2025",
}) => {
  return (
    <div className="min-h-screen bg-background py-12 px-4 sm:px-6 lg:px-8">
      <div className="fixed top-5 left-5">
        <a
          href="/#footer"
          className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
        >
          <CircleChevronLeft size={30} />
        </a>
      </div>
      <div className="max-w-4xl mx-auto bg-slate-900/50 backdrop-blur-sm rounded-lg shadow-xl p-8 md:p-12">
        <h1 className="text-4xl font-bold text-white mb-4">
          Terms & Conditions
        </h1>
        <p className="text-slate-400 mb-8">Last Updated: {lastUpdated}</p>

        <div className="space-y-8 text-slate-300">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              1. Acceptance of Terms
            </h2>
            <p className="leading-relaxed">
              By accessing or using {companyName} ("Service," "Platform," "we,"
              "us," or "our"), you agree to be bound by these Terms &
              Conditions. If you do not agree to these terms, please do not use
              our Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              2. Description of Service
            </h2>
            <p className="leading-relaxed mb-4">
              {companyName} is an AI-powered platform that enables users to
              create, optimize, and distribute product advertisements across
              multiple social media platforms. Our Service includes:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>AI-generated video content from product photos</li>
              <li>Multi-platform content optimization</li>
              <li>Automated scheduling and posting</li>
              <li>Cross-platform distribution tools</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              3. User Accounts
            </h2>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              3.1 Registration
            </h3>
            <p className="leading-relaxed">
              You must create an account to use {companyName}. You agree to
              provide accurate, current, and complete information during
              registration and to update such information to keep it accurate,
              current, and complete.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              3.2 Account Security
            </h3>
            <p className="leading-relaxed">
              You are responsible for maintaining the confidentiality of your
              account credentials and for all activities that occur under your
              account. You agree to notify us immediately of any unauthorized
              use of your account.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              3.3 Account Eligibility
            </h3>
            <p className="leading-relaxed">
              You must be at least 18 years old or the age of majority in your
              jurisdiction to use
              {companyName}. By using our Service, you represent and warrant
              that you meet these requirements.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              4. Content and Intellectual Property
            </h2>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              4.1 Your Content
            </h3>
            <p className="leading-relaxed">
              You retain all rights to the product photos and materials you
              upload to {companyName}. By uploading content, you grant us a
              worldwide, non-exclusive, royalty-free license to use, reproduce,
              modify, and process your content solely for the purpose of
              providing our Service.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              4.2 AI-Generated Content
            </h3>
            <p className="leading-relaxed">
              Content generated by our AI technology is provided to you for your
              use in accordance with these Terms. You are responsible for
              reviewing and approving all AI-generated content before
              distribution.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              4.3 Platform Ownership
            </h3>
            <p className="leading-relaxed">
              {companyName}, including all software, algorithms, designs, and
              technology, is owned by us and protected by intellectual property
              laws. You may not copy, modify, distribute, or reverse engineer
              any part of our Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              5. User Responsibilities
            </h2>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              5.1 Content Compliance
            </h3>
            <p className="leading-relaxed mb-4">
              You agree that all content you upload and distribute through{" "}
              {companyName}:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>
                Does not infringe on any third-party intellectual property
                rights
              </li>
              <li>Does not contain illegal, harmful, or offensive material</li>
              <li>
                Complies with all applicable advertising laws and regulations
              </li>
              <li>
                Does not violate the terms of service of destination platforms
              </li>
              <li>
                Does not contain false or misleading claims about products or
                services
              </li>
            </ul>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              5.2 Platform Accounts
            </h3>
            <p className="leading-relaxed">
              You are responsible for connecting and maintaining valid accounts
              on third-party platforms. You must comply with each platform's
              terms of service and advertising policies.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              5.3 Monitoring
            </h3>
            <p className="leading-relaxed">
              You acknowledge that we do not pre-screen content but reserve the
              right to remove or refuse to distribute any content that violates
              these Terms or applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              6. Prohibited Uses
            </h2>
            <p className="leading-relaxed mb-4">
              You agree not to use {companyName} to:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Violate any laws or regulations</li>
              <li>Infringe upon intellectual property rights</li>
              <li>Distribute spam, malware, or harmful content</li>
              <li>Engage in fraudulent or deceptive practices</li>
              <li>Promote illegal products or services</li>
              <li>Harass, abuse, or harm others</li>
              <li>Interfere with the proper functioning of the Service</li>
              <li>Attempt to gain unauthorized access to our systems</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              7. Third-Party Platforms
            </h2>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              7.1 Platform Integration
            </h3>
            <p className="leading-relaxed">
              {companyName} integrates with third-party social media platforms.
              We are not responsible for the availability, functionality, or
              policies of these platforms.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              7.2 Platform Changes
            </h3>
            <p className="leading-relaxed">
              Third-party platforms may change their APIs, policies, or features
              at any time, which may affect our Service's functionality. We are
              not liable for any disruptions caused by third-party platform
              changes.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              7.3 Platform Account Issues
            </h3>
            <p className="leading-relaxed">
              You are solely responsible for any issues with your third-party
              platform accounts, including suspensions, bans, or policy
              violations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              8. Fees, Payment, and Credits
            </h2>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              8.1 Subscription Fees
            </h3>
            <p className="leading-relaxed">
              Access to {companyName} may require payment of subscription fees.
              All fees are as described on our pricing page at the time of
              purchase.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              8.2 Credits
            </h3>
            <p className="leading-relaxed">
              Users purchase credits to generate AI-powered content. Unused
              credits roll over month to month and never expire. You can cancel
              your subscription at any time and retain any unused credits.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              8.3 Refunds
            </h3>
            <p className="leading-relaxed">
              Subscription fees are generally non-refundable. However, any
              unused credits are retained as described above.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              8.4 Billing & Price Changes
            </h3>
            <p className="leading-relaxed">
              Subscription fees are billed in advance on a recurring basis
              (monthly or annually, as selected). We reserve the right to change
              our pricing with at least 30 days' notice to active subscribers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              9. Disclaimers and Limitations of Liability
            </h2>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              9.1 Service Availability
            </h3>
            <p className="leading-relaxed">
              {companyName} is provided "as is" and "as available" without
              warranties of any kind, either express or implied. We do not
              guarantee uninterrupted or error-free service.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              9.2 AI-Generated Content
            </h3>
            <p className="leading-relaxed">
              While our AI technology strives for quality, we do not guarantee
              the accuracy, appropriateness, or effectiveness of AI-generated
              content. You are responsible for reviewing and approving all
              content before distribution.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              9.3 Performance Results
            </h3>
            <p className="leading-relaxed">
              We make no guarantees regarding the performance, engagement, or
              results of ads created and distributed through {companyName}.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              9.4 Limitation of Liability
            </h3>
            <p className="leading-relaxed">
              To the maximum extent permitted by law, {companyName} and its
              affiliates shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages, or any loss of
              profits or revenues, whether incurred directly or indirectly, or
              any loss of data, use, goodwill, or other intangible losses
              resulting from your use or inability to use the Service.
            </p>
            <p className="leading-relaxed mt-4">
              Our total liability shall not exceed the amount you paid to us in
              the twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              10. Indemnification
            </h2>
            <p className="leading-relaxed">
              You agree to indemnify, defend, and hold harmless {companyName},
              its affiliates, officers, directors, employees, and agents from
              any claims, damages, losses, liabilities, and expenses (including
              legal fees) arising from:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4 mt-4">
              <li>Your use of the Service</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any third-party rights</li>
              <li>Content you upload or distribute through the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              11. Termination
            </h2>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              11.1 Termination by You
            </h3>
            <p className="leading-relaxed">
              You may terminate your account at any time through your account
              settings or by contacting us.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              11.2 Termination by Us
            </h3>
            <p className="leading-relaxed">
              We reserve the right to suspend or terminate your account if you
              violate these Terms, engage in fraudulent activity, or for any
              other reason at our discretion.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              11.3 Effect of Termination
            </h3>
            <p className="leading-relaxed">
              Upon termination, your right to use {companyName} will immediately
              cease. We may delete your data in accordance with our Privacy
              Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              12. Modifications to Terms
            </h2>
            <p className="leading-relaxed">
              We may modify these Terms at any time. We will notify you of
              material changes via email or through the Service. Your continued
              use of {companyName} after such notification constitutes
              acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              13. Governing Law and Dispute Resolution
            </h2>
            <p className="leading-relaxed mb-4">
              These Terms shall be governed by and construed in accordance with
              applicable laws, without regard to conflict of law provisions.
            </p>
            <p className="leading-relaxed">
              Any disputes arising from these Terms or your use of {companyName}{" "}
              shall be resolved through binding arbitration where permitted by
              law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              14. General Provisions
            </h2>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              14.1 Entire Agreement
            </h3>
            <p className="leading-relaxed">
              These Terms constitute the entire agreement between you and{" "}
              {companyName} regarding the Service.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              14.2 Severability
            </h3>
            <p className="leading-relaxed">
              If any provision of these Terms is found to be invalid or
              unenforceable, the remaining provisions will remain in full force
              and effect.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              14.3 Waiver
            </h3>
            <p className="leading-relaxed">
              Our failure to enforce any right or provision of these Terms will
              not be considered a waiver of those rights.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">
              14.4 Assignment
            </h3>
            <p className="leading-relaxed">
              You may not assign or transfer these Terms without our prior
              written consent. We may assign our rights without restriction.
            </p>
          </section>
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              15. Third-Party Platform Integrations
            </h2>
            <p className="leading-relaxed mb-4">
              {companyName} may connect with third-party social media platforms
              (such as TikTok, Instagram, Facebook, YouTube, and LinkedIn) to
              enable posting, scheduling, and analytics of your content.
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>
                <strong className="text-white">Data Shared:</strong> Only
                necessary account information, authentication tokens, and
                AI-generated content required to provide the Service.
              </li>
              <li>
                <strong className="text-white">Purpose:</strong> To create,
                optimize, schedule, and analyze advertisements on connected
                platforms.
              </li>
              <li>
                <strong className="text-white">User Control:</strong> You can
                disconnect any platform at any time through your account
                settings, which will revoke {companyName}'s access.
              </li>
              <li>
                <strong className="text-white">Platform Policies:</strong> Each
                platform's use of your information is subject to their own
                privacy policies, and you must comply with them.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">
              16. Contact Information
            </h2>
            <p className="leading-relaxed mb-4">
              For questions about these Terms & Conditions, please contact us
              at:
            </p>
            <div className="p-4 bg-slate-800/50 rounded-lg">
              <p className="text-blue-400 font-medium">Email: {contactEmail}</p>
            </div>
          </section>

          <div className="mt-12 pt-8 border-t border-slate-700 text-center">
            <p className="text-slate-400">
              By using {companyName}, you acknowledge that you have read,
              understood, and agree to be bound by these Terms & Conditions.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
